"""The report's outline, computed from the graph.

Spec section 7: "The outline is computed, not invented. Root task
branches become top-level sections; each hypothesis and fact is assigned
to the branch its provenance lies in." The outliner subagent may reorder
and retitle what this produces; `validate` is what stops it doing
anything else.

A section is derived state, not a memory node. It is recomputable from
the graph plus the outliner's artifact, so it gets no node type, no
directory under memory/, and no fsck rule — it lives at out/outline.json
and can be regenerated by re-running `research synthesize`.
"""
import graph as graph_mod
import ids as ids_mod

PATH_NAME = "outline.json"

# The cross-cutting Synthesis section. Reserved rather than sequential:
# theme sections number from S-001 upward, and this one is seeded by
# apply_outline OUTSIDE the outline's own section list, because it needs
# every theme's hypotheses at once while `validate` requires each
# hypothesis be assigned exactly once. Collides only at 999 themes.
SYNTHESIS_SECTION_ID = "S-999"

# Spec section 7 assigns findings to sections; a refuted hypothesis is
# still reported, but in Appendix A and B rather than narrated in the body
# as though it were a finding.
BODY_HYPOTHESIS_STATUSES = ("proposed", "supported", "contested")

# Synthesis's own tasks are not research themes. `research synthesize`
# seeds an `outline` task and applying it seeds one `synthesize` task per
# section; both live in the same task store as everything else. Theme
# COLLECTION no longer needs this list — `_themes` keys on the run root's
# children instead, and neither an outline nor a synthesize task is one —
# but `place` still does: it resolves a theme straight off
# `provenance.task`, so a hypothesis or fact anchored directly on a
# machinery task would otherwise be promoted into a real report section,
# putting the report's own machinery in a chapter.
MACHINERY_KINDS = ("outline", "synthesize")

# Kinds that must never title a chapter. MACHINERY_KINDS plus the one
# scheduler round `_themes` already excludes and `place` used to re-admit:
# apply.ensure_hypothesize_tasks parents every `hypothesize` task on
# `branch_of(...)` -> Graph.root_branch, a constant function on a real
# run, so each round is a depth-0 child of the root and `theme_of`
# resolves it to itself. Measured on a driven run, that put nine chapters
# titled "Form candidate claims from the N facts gathered under: ..." in
# the report, each holding the same claim.
#
# Separate from MACHINERY_KINDS because that constant means something
# else — the report-production half of the kind enum, which render.py
# reads to decide what counts as a line of enquiry in Limitations. A
# `hypothesize` task IS research; it just is not a chapter.
NON_THEME_KINDS = MACHINERY_KINDS + ("hypothesize",)

# The kinds a decomposer is permitted to propose as a child, taken from
# `children[].kind` in schemas/artifact.decompose.json. Anchored to that
# enum on purpose: a theme is exactly a line of enquiry a decomposer
# opened, so this list must not drift from what one can actually create.
THEME_KINDS = ("decompose", "search")


def run_root(graph):
    """The run's own seeded root task, or None if the store holds none.

    `parent is None` alone does NOT identify it. A live run holds two
    parentless tasks: this one, and the `outline` task `synthesis.seed`
    creates at depth 0. The `kind` clause is what separates them —
    `workspace.seed_root_task` is the only thing in the system that
    creates a parentless `decompose` task, and `apply_decompose` only ever
    creates children with a parent set.

    Lowest id wins, so the answer is deterministic on a hand-built or
    corrupted store holding more than one candidate.
    """
    candidates = [
        task_id for task_id, task in graph.tasks.items()
        # `.get`, not `[...]`: graph.tasks keeps every task that merely
        # parses, and a task that failed its schema may be missing either
        # of these required fields.
        if task.get("parent") is None and task.get("kind") == "decompose"
    ]
    return min(candidates, key=ids_mod.numeric) if candidates else None


def _themes(graph):
    """The report's top-level themes: the run root's own children.

    Spec section 7: "Root task branches become top-level sections." A
    theme is a child of the run root whose kind a decomposer could have
    proposed — nothing else.

    What this replaced collected `theme_of(t)` for every task, which swept
    in two things that are not lines of enquiry and reported both in
    Appendix C as unresolved open questions:

    - the run root itself. `theme_of(root)` is root — it has no depth-1
      ancestor, "the one task where the distinction is meaningless" — and
      the root carries no hypotheses or facts directly, so EVERY report
      listed its own question as a direction that produced no findings;
    - the `hypothesize` task `apply.ensure_hypothesize_tasks` schedules on
      `root_branch`, i.e. parented on the root at the root's own depth,
      which `theme_of` therefore resolves to itself. It is code-scheduled
      machinery, and MACHINERY_KINDS does not cover its kind.

    A theme that genuinely produced nothing is still a child of the root
    and is still collected here, so it still reaches `empty_themes` and
    Appendix C. Hiding those would overstate how completely the question
    was covered — a worse defect than the one this fixes.
    """
    root = run_root(graph)
    if root is None:
        # Nothing can be a child of a root that does not exist. Returning
        # every parentless task instead would make `research synthesize`'s
        # own outline task a theme on a store that never seeded a root.
        return []
    return sorted(
        (task_id for task_id, task in graph.tasks.items()
         if task.get("parent") == root and task.get("kind") in THEME_KINDS),
        key=ids_mod.numeric,
    )


def _theme(graph, task_id):
    """The theme a task belongs to, or None if it cannot be determined.

    Total by construction. `theme_of` walks parent links and raises
    CycleError on a cycle, and a node written by an agent can name a
    provenance task that was later deleted. Neither is worth losing the
    whole report over: an unplaceable finding becomes an orphan, which
    Appendix C reports.
    """
    if not task_id or task_id not in graph.tasks:
        return None
    try:
        return graph.theme_of(task_id)
    except graph_mod.CycleError:
        return None


def _citation_themes(graph):
    """{citation id: the theme of an active fact citing it}.

    Built once per `compute`: a long run holds hundreds of facts and
    hundreds of citations, and resolving this per hypothesis is
    quadratic.

    A citation cited by facts under two themes keeps the lowest by id,
    which only decides a tie nobody can decide better.
    """
    found = {}
    for _, fact in graph.readable("fact"):
        if fact["status"] != "active":
            continue
        theme = _theme(graph, (fact.get("provenance") or {}).get("task"))
        if theme is None:
            continue
        for citation_id in fact["citations"]:
            current = found.get(citation_id)
            if current is None or ids_mod.numeric(theme) < ids_mod.numeric(current):
                found[citation_id] = theme
    return found


def _theme_of_hypothesis(graph, hypothesis, citation_themes):
    """The theme a finding belongs under: where its EVIDENCE came from.

    Not `provenance.task`, which is the hypothesize round that proposed
    it. `apply.ensure_hypothesize_tasks` parents every round on
    `branch_of(...)` -> `Graph.root_branch`, "on a real run a constant
    function" — the seeded root. So every round is a depth-0 child of
    the root, `theme_of` resolves it to itself, and `place` below
    registered a bucket for it rather than lose the finding. Measured on
    a driven run: nine chapters titled "Form candidate claims from the N
    facts gathered under: ...", each holding the same claim, and the one
    real theme holding no findings at all.

    `place`'s original choice was between a bookkeeping chapter and a
    lost finding, and it took the first. This is the third option: a
    reader expects a chapter to be a line of enquiry, and a finding
    belongs with the enquiry that produced the evidence for it. Facts
    already work this way — a fact's provenance is its `extract` task,
    which sits under a `search` task under a real theme.

    Most common theme wins; ties go to the lowest task id so the result
    is deterministic. A claim genuinely spanning two enquiries lands in
    the one that supplied most of its support — imperfect, and better
    than filing it under a scheduler round.

    `counter` citations do not vote. A claim is not ABOUT the enquiry
    that tried to break it, and letting them count would mean a
    successful refute search relocates the finding it challenged.

    Returns None when nothing resolves, and the caller falls back to
    the old provenance rollup. A claim with no live evidence is already
    reported as open; it must still be placed or orphaned, never
    dropped.
    """
    votes = {}
    for citation_id in hypothesis.get("supporting") or ():
        theme = citation_themes.get(citation_id)
        if theme is not None:
            votes[theme] = votes.get(theme, 0) + 1
    if not votes:
        return None
    return min(votes, key=lambda theme: (-votes[theme], ids_mod.numeric(theme)))


def _theme_via_challenged_claim(graph, node, citation_themes):
    """The theme of the hypothesis a refute search was gathered against.

    A refutation's evidence belongs with the claim it challenges, not
    with the scheduler round that happened to raise that claim. The
    chain is: fact -> its `extract` task, which `apply_search` tagged
    with `inputs.for_hypothesis` when the search's stance was `against`
    -> that hypothesis -> the theme its own evidence rolls up to.

    None when the node is not refutation evidence, or when the claim it
    challenges cannot itself be placed. The caller keeps whatever it had.
    """
    task_id = (node.get("provenance") or {}).get("task")
    target = ((graph.tasks.get(task_id) or {}).get("inputs")
              or {}).get("for_hypothesis")
    if not target:
        return None
    try:
        hypothesis = graph.memory.read(target)
    except Exception:
        return None
    return _theme_of_hypothesis(graph, hypothesis, citation_themes)


def compute(graph, cfg):
    """The outline, derived entirely from the graph. Pure: no writes."""
    themes = _themes(graph)
    citation_themes = _citation_themes(graph)
    buckets = {theme: {"hypotheses": [], "facts": []} for theme in themes}
    orphans = {"hypotheses": [], "facts": []}

    def place(bucket_key, node_id, node):
        theme = None
        if bucket_key == "hypotheses":
            # Evidence first: see _theme_of_hypothesis. Falls through to
            # the provenance rollup below when nothing resolves, which is
            # what keeps a claim with no live evidence placed or
            # orphaned rather than dropped.
            theme = _theme_of_hypothesis(graph, node, citation_themes)
        if theme is None:
            theme = _theme(graph, (node.get("provenance") or {}).get("task"))
        # A refutation belongs with the claim it challenges.
        # ensure_refute_tasks parents a refute search on its target's
        # provenance task — a hypothesize round — so the extract beneath
        # it, and the counter-evidence fact beneath that, all roll up to
        # a scheduler round. apply_search propagates `for_hypothesis`
        # onto the extract for exactly this stance, so the real rollup
        # point is already on the node.
        if graph.tasks.get(theme, {}).get("kind") == "hypothesize":
            rescued = _theme_via_challenged_claim(graph, node, citation_themes)
            if rescued is not None:
                theme = rescued
        # A theme can reach here without a bucket already declared by
        # `_themes`: that function collects the run root's own children,
        # while this path resolves a rollup point independently, straight
        # off `provenance.task`. A finding raised under a task that is not
        # one of those children — the code-scheduled `hypothesize` task,
        # say, which `theme_of` resolves to itself — has a perfectly
        # determinate rollup point even so, and dropping it to `orphans`
        # would lose a real finding out of the body. `setdefault`
        # registers the bucket on first use instead.
        #
        # A theme registered this way always carries the node that
        # registered it, so it can never end up in `empty_themes`: every
        # entry there comes from `_themes`, which is what keeps Appendix C
        # to lines of enquiry a decomposer actually opened.
        #
        # The MACHINERY_KINDS check is what this path needs and `_themes`
        # does not: neither an `outline` task (parentless) nor a
        # `synthesize` task (parented on the outline task) is a child of
        # the run root, so neither can reach `_themes` at all. Here, a
        # hypothesis or fact anchored directly on one would otherwise be
        # promoted into a real report section, putting the report's own
        # machinery in a chapter.
        if theme is None or graph.tasks.get(theme, {}).get("kind") in NON_THEME_KINDS:
            orphans[bucket_key].append(node_id)
        else:
            buckets.setdefault(theme, {"hypotheses": [], "facts": []})
            buckets[theme][bucket_key].append(node_id)

    for hypothesis_id, hypothesis in graph.readable("hypothesis"):
        if hypothesis["status"] in BODY_HYPOTHESIS_STATUSES:
            place("hypotheses", hypothesis_id, hypothesis)
    for fact_id, fact in graph.readable("fact"):
        if fact["status"] == "active":
            place("facts", fact_id, fact)

    # Re-derive from `buckets` rather than unioning it with the original
    # `themes`: `buckets` was seeded from `themes` above and `place` only
    # ever adds keys to it (via `setdefault`), never removes any, so
    # `buckets` is already a superset of `themes` by construction — the
    # union was provably a no-op. This is what makes a theme discovered
    # only via placement (see the comment in `place`) get a section like
    # any other.
    collected = sorted(buckets, key=ids_mod.numeric)

    sections = []
    for theme in collected:
        bucket = buckets[theme]
        # A theme that carries nothing is not a section: rendering it would
        # put a blank chapter in the report. Only a theme from `_themes`
        # can be empty here — see the comment in `place` — so this skip and
        # `empty_themes` below always describe the same set.
        if not bucket["hypotheses"] and not bucket["facts"]:
            continue
        # `.get`, not `[...]`: graph.tasks keeps tasks that parse but fail
        # their schema, and such a task may have no `question` at all.
        title = (graph.tasks.get(theme, {}).get("question") or "").strip()
        sections.append({
            "id": f"S-{len(sections) + 1:03d}",
            "theme": theme,
            "title": title or f"Findings from {theme}",
            "hypotheses": sorted(bucket["hypotheses"], key=ids_mod.numeric),
            "facts": sorted(bucket["facts"], key=ids_mod.numeric),
        })

    placed = {section["theme"] for section in sections}
    return {
        "question": cfg["question"],
        "sections": sections,
        "orphans": {key: sorted(value, key=ids_mod.numeric)
                    for key, value in orphans.items()},
        "empty_themes": [theme for theme in themes if theme not in placed],
    }


def _multiset_errors(label, wanted, seen):
    """Dropped / invented / duplicated, as three independent findings."""
    errors = []
    duplicated = sorted({item for item in seen if seen.count(item) > 1})
    if duplicated:
        errors.append(
            f"{label} assigned to more than one section: "
            + ", ".join(duplicated))
    dropped = sorted(set(wanted) - set(seen))
    if dropped:
        errors.append(f"{label} dropped from the outline: " + ", ".join(dropped))
    invented = sorted(set(seen) - set(wanted))
    if invented:
        errors.append(
            f"{label} not in the computed outline: " + ", ".join(invented))
    return errors


def validate(computed, artifact):
    """Every way the outliner's result can fail against its input.

    Returns a list rather than raising on the first problem. apply_outline
    puts the whole list into the rejection message, so one retry can fix
    everything at once; surfacing them one at a time would spend all three
    attempts on three separate complaints.
    """
    errors = []
    sections = artifact.get("sections") or []

    wanted_ids = [section["id"] for section in computed["sections"]]
    seen_ids = [section.get("id") for section in sections]
    errors += _multiset_errors("section", wanted_ids,
                               [i for i in seen_ids if i is not None])
    if any(section.get("id") is None for section in sections):
        errors.append("a section in the artifact has no id")

    for key, label in (("hypotheses", "hypothesis"), ("facts", "fact")):
        wanted = [item for section in computed["sections"] for item in section[key]]
        seen = [item for section in sections for item in (section.get(key) or [])]
        errors += _multiset_errors(label, wanted, seen)

    for section in sections:
        if not (section.get("title") or "").strip():
            errors.append(
                f"{section.get('id', 'a section')} has an empty title")
        # `compute`'s own rule, re-applied here. The checks above are
        # multisets over ALL sections combined, and outliner.md explicitly
        # licenses moving a finding from one section to another — so an
        # outliner that consolidates everything into one section and
        # leaves another empty passes every one of them. apply_outline
        # would then seed that section's writer with hypotheses [], facts
        # [] and allowed_cite_keys [], and gate 5 only rejects a sentence
        # carrying a DIGIT with no provenance: unmarked qualitative prose
        # goes straight through. The result is a chapter of the report
        # with no evidence under it at all, written entirely by the model.
        # Reported rather than raised, so the outliner can fix it on retry
        # along with everything else.
        if not (section.get("hypotheses") or section.get("facts")):
            errors.append(
                f"{section.get('id', 'a section')} carries neither a "
                "hypothesis nor a fact; every section must keep at least "
                "one finding, so move one back into it. Dropping the "
                "section instead is not allowed — every computed section "
                "must appear exactly once.")
    return errors


def apply_artifact(computed, artifact):
    """The accepted outline: the artifact's order, titles and assignments,
    the computed outline's topology.

    `theme` is never taken from the artifact. It is graph topology, the
    outliner never receives it, and both Appendix C and render's retry path
    resolve a section back to its theme task through this field — a model
    able to change it could point the build-failure retry at the wrong task.
    """
    by_id = {section["id"]: section for section in computed["sections"]}
    sections = []
    for edited in artifact["sections"]:
        original = by_id[edited["id"]]
        sections.append({
            "id": original["id"],
            "theme": original["theme"],
            "title": edited["title"].strip(),
            "hypotheses": sorted(edited.get("hypotheses") or [],
                                 key=ids_mod.numeric),
            "facts": sorted(edited.get("facts") or [], key=ids_mod.numeric),
        })
    return {**computed, "sections": sections}
